[package]
name = "catsay"
version = "0.1.0"
authors = ["Guillermo Fern√°ndez <guillermo.fernandez.283@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
colored = "2.1.0"
